/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectsem2;

import java.awt.*;

/**
 *
 * @author KHANH VY
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblAdd = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblAdd1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblAdd2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblAdd3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblAdd4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblAdd5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblAdd6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 181, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 25)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        lblAdd.setText("   Sale");
        lblAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddMouseExited(evt);
            }
        });
        jPanel3.add(lblAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 310, 160));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 340, 180));

        jPanel4.setBackground(new java.awt.Color(0, 181, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdd1.setFont(new java.awt.Font("Trebuchet MS", 0, 25)); // NOI18N
        lblAdd1.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/text-book-opened-from-top-view.png"))); // NOI18N
        lblAdd1.setText("   Products");
        lblAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAdd1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdd1MouseExited(evt);
            }
        });
        jPanel4.add(lblAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 320, 150));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 340, 180));

        jPanel5.setBackground(new java.awt.Color(0, 181, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdd2.setFont(new java.awt.Font("Trebuchet MS", 0, 25)); // NOI18N
        lblAdd2.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about.png"))); // NOI18N
        lblAdd2.setText("    Human Resource");
        lblAdd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAdd2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdd2MouseExited(evt);
            }
        });
        jPanel5.add(lblAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 320, 150));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 340, 180));

        jPanel6.setBackground(new java.awt.Color(0, 181, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdd3.setFont(new java.awt.Font("Trebuchet MS", 0, 25)); // NOI18N
        lblAdd3.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sale.png"))); // NOI18N
        lblAdd3.setText("  Statistic");
        lblAdd3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAdd3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdd3MouseExited(evt);
            }
        });
        jPanel6.add(lblAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 160));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 340, 180));

        jPanel7.setBackground(new java.awt.Color(0, 181, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdd4.setFont(new java.awt.Font("Trebuchet MS", 0, 25)); // NOI18N
        lblAdd4.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about.png"))); // NOI18N
        lblAdd4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAdd4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdd4MouseExited(evt);
            }
        });
        jPanel7.add(lblAdd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 320, 150));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 340, 180));

        jPanel8.setBackground(new java.awt.Color(0, 181, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdd5.setFont(new java.awt.Font("Trebuchet MS", 0, 25)); // NOI18N
        lblAdd5.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        lblAdd5.setText("    Logout");
        lblAdd5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAdd5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdd5MouseExited(evt);
            }
        });
        jPanel8.add(lblAdd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 160));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 340, 180));

        jPanel9.setBackground(new java.awt.Color(0, 181, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdd6.setFont(new java.awt.Font("Trebuchet MS", 0, 25)); // NOI18N
        lblAdd6.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        lblAdd6.setText("Logout");
        lblAdd6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAdd6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdd6MouseExited(evt);
            }
        });
        jPanel9.add(lblAdd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 150, 70));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, 70));

        jPanel2.setBackground(new java.awt.Color(0, 181, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hai Chau District, Da Nang City, Vietnam.");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ABC Bookstore");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1256, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseEntered

    private void lblAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseEntered
        Color clr = new Color(0, 153, 204);
        jPanel3.setBackground(clr);
    }//GEN-LAST:event_lblAddMouseEntered

    private void lblAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseExited
        Color clr = new Color(0, 181, 204);
        jPanel3.setBackground(clr);
    }//GEN-LAST:event_lblAddMouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseEntered

    private void lblAdd2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdd2MouseExited
        Color clr = new Color(0, 181, 204);
        jPanel5.setBackground(clr);
    }//GEN-LAST:event_lblAdd2MouseExited

    private void lblAdd2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdd2MouseEntered
        Color clr = new Color(0, 153, 204);
        jPanel5.setBackground(clr);
    }//GEN-LAST:event_lblAdd2MouseEntered

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseEntered

    private void lblAdd1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdd1MouseExited
        Color clr = new Color(0, 181, 204);
        jPanel4.setBackground(clr);
    }//GEN-LAST:event_lblAdd1MouseExited

    private void lblAdd1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdd1MouseEntered
        Color clr = new Color(0, 153, 204);
        jPanel4.setBackground(clr);
    }//GEN-LAST:event_lblAdd1MouseEntered

    private void lblAdd3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdd3MouseEntered
        Color clr = new Color(0, 153, 204);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_lblAdd3MouseEntered

    private void lblAdd3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdd3MouseExited
        Color clr = new Color(0, 181, 204);
        jPanel6.setBackground(clr);
    }//GEN-LAST:event_lblAdd3MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseEntered

    private void lblAdd4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdd4MouseEntered
        Color clr = new Color(0, 153, 204);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_lblAdd4MouseEntered

    private void lblAdd4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdd4MouseExited
        Color clr = new Color(0, 181, 204);
        jPanel7.setBackground(clr);
    }//GEN-LAST:event_lblAdd4MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseEntered

    private void lblAdd5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdd5MouseEntered
        Color clr = new Color(0, 153, 204);
        jPanel8.setBackground(clr);
    }//GEN-LAST:event_lblAdd5MouseEntered

    private void lblAdd5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdd5MouseExited
        Color clr = new Color(0, 181, 204);
        jPanel8.setBackground(clr);
    }//GEN-LAST:event_lblAdd5MouseExited

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseEntered

    private void lblAdd6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdd6MouseEntered
        Color clr = new Color(0, 153, 204);
        jPanel9.setBackground(clr);
    }//GEN-LAST:event_lblAdd6MouseEntered

    private void lblAdd6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdd6MouseExited
        Color clr = new Color(0, 181, 204);
        jPanel9.setBackground(clr);
    }//GEN-LAST:event_lblAdd6MouseExited

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblAdd1;
    private javax.swing.JLabel lblAdd2;
    private javax.swing.JLabel lblAdd3;
    private javax.swing.JLabel lblAdd4;
    private javax.swing.JLabel lblAdd5;
    private javax.swing.JLabel lblAdd6;
    // End of variables declaration//GEN-END:variables
}
