/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Model.BookModify;
import Model.Books;
import Model.HoverEffect;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KHANH VY
 */
public class BookStorageForm extends javax.swing.JPanel {

    ArrayList<Books> booksList = new ArrayList<>();
    DefaultTableModel  tableModelBook;
    byte[] bookImage;
    /**
     * Creates new form BookStorageForm
     */
    public BookStorageForm() {
        initComponents();
        tableModelBook = (DefaultTableModel) tblBook.getModel();
        showBook();
        PnlEditBook.setVisible(false);
        lblResetBook.setVisible(false);
    }

    public void showBook() {
        //employeeList = EmployeeModify.findAll();
        booksList = BookModify.findAllBooks();

        tableModelBook.setRowCount(0);
        booksList.forEach((b) -> {
            tableModelBook.addRow(new Object[]{/*tableModel.getRowCount() + 1 ,*/b.getBookId().trim(), b.getBookName(), b.getAuthor(),
                b.getGenre(), b.getPublisher(), b.getQuantity(), b.getPrice()});
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBook = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        lblBookImage = new javax.swing.JLabel();
        txtSearchBook = new javax.swing.JTextField();
        btnSearchBook = new javax.swing.JPanel();
        lblSearchBook = new javax.swing.JLabel();
        lblResetBook = new javax.swing.JLabel();
        btnEditBook = new javax.swing.JPanel();
        lblEditBook = new javax.swing.JLabel();
        PnlEditBook = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtGenre = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        btnchooseImg = new javax.swing.JButton();
        txtBookName = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtPublisher = new javax.swing.JTextField();
        btnEditBook2 = new javax.swing.JPanel();
        lblEditBook2 = new javax.swing.JLabel();
        lblErrEdit = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        lblEditImg = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnEditExit = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        tblBook.setAutoCreateRowSorter(true);
        tblBook.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblBook.setForeground(new java.awt.Color(153, 153, 153));
        tblBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "BookId", "Name", "Author", "Genre", "Publisher", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBook.setGridColor(new java.awt.Color(255, 255, 255));
        tblBook.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblBook.setRowHeight(25);
        tblBook.setSelectionBackground(new java.awt.Color(0, 181, 204));
        tblBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBook);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBookImage, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBookImage, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        txtSearchBook.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtSearchBook.setForeground(new java.awt.Color(204, 204, 204));
        txtSearchBook.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        btnSearchBook.setBackground(new java.awt.Color(255, 255, 255));

        lblSearchBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search2.png"))); // NOI18N
        lblSearchBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSearchBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSearchBookMouseExited(evt);
            }
        });

        lblResetBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        lblResetBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblResetBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblResetBookMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSearchBookLayout = new javax.swing.GroupLayout(btnSearchBook);
        btnSearchBook.setLayout(btnSearchBookLayout);
        btnSearchBookLayout.setHorizontalGroup(
            btnSearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSearchBookLayout.createSequentialGroup()
                .addComponent(lblSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblResetBook)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        btnSearchBookLayout.setVerticalGroup(
            btnSearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSearchBookLayout.createSequentialGroup()
                .addComponent(lblSearchBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addComponent(lblResetBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnEditBook.setBackground(new java.awt.Color(0, 181, 204));

        lblEditBook.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        lblEditBook.setForeground(new java.awt.Color(255, 255, 255));
        lblEditBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        lblEditBook.setText("Edit");
        lblEditBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEditBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEditBookMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEditBookLayout = new javax.swing.GroupLayout(btnEditBook);
        btnEditBook.setLayout(btnEditBookLayout);
        btnEditBookLayout.setHorizontalGroup(
            btnEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEditBook, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );
        btnEditBookLayout.setVerticalGroup(
            btnEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEditBookLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblEditBook))
        );

        PnlEditBook.setBackground(new java.awt.Color(255, 255, 255));
        PnlEditBook.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Book Name");

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Author");

        txtGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novel", "Children", "Science-Technology", "Literature-Art", "Lifestyle", "Education", "Politics-Laws", "Culture-Social" }));
        txtGenre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(204, 204, 204)));

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Publisher");

        btnchooseImg.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnchooseImg.setText("choose Image");
        btnchooseImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchooseImgActionPerformed(evt);
            }
        });

        txtBookName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtBookName.setForeground(new java.awt.Color(204, 204, 204));
        txtBookName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtAuthor.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtAuthor.setForeground(new java.awt.Color(204, 204, 204));
        txtAuthor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtPublisher.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtPublisher.setForeground(new java.awt.Color(204, 204, 204));
        txtPublisher.setToolTipText("");
        txtPublisher.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        btnEditBook2.setBackground(new java.awt.Color(0, 181, 204));

        lblEditBook2.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        lblEditBook2.setForeground(new java.awt.Color(255, 255, 255));
        lblEditBook2.setText(" Edit");
        lblEditBook2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditBook2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEditBook2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEditBook2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEditBook2Layout = new javax.swing.GroupLayout(btnEditBook2);
        btnEditBook2.setLayout(btnEditBook2Layout);
        btnEditBook2Layout.setHorizontalGroup(
            btnEditBook2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEditBook2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );
        btnEditBook2Layout.setVerticalGroup(
            btnEditBook2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEditBook2Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(lblEditBook2))
        );

        lblErrEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        lblErrEdit.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEditImg, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEditImg, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setText("Genre");

        btnEditExit.setFont(new java.awt.Font("Trebuchet MS", 1, 21)); // NOI18N
        btnEditExit.setForeground(new java.awt.Color(0, 181, 204));
        btnEditExit.setText("X");
        btnEditExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditExitMouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout PnlEditBookLayout = new javax.swing.GroupLayout(PnlEditBook);
        PnlEditBook.setLayout(PnlEditBookLayout);
        PnlEditBookLayout.setHorizontalGroup(
            PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlEditBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlEditBookLayout.createSequentialGroup()
                        .addComponent(btnchooseImg, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditBook2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblErrEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlEditBookLayout.createSequentialGroup()
                        .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PnlEditBookLayout.createSequentialGroup()
                                .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBookName, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                    .addComponent(txtAuthor)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlEditBookLayout.createSequentialGroup()
                                .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGenre, 0, 295, Short.MAX_VALUE)
                                    .addComponent(txtPublisher)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlEditBookLayout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)))
                        .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlEditBookLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 45, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlEditBookLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditExit)))))
                .addContainerGap())
        );
        PnlEditBookLayout.setVerticalGroup(
            PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlEditBookLayout.createSequentialGroup()
                .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlEditBookLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditExit)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(33, 33, 33)
                        .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtPublisher)))
                    .addGroup(PnlEditBookLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlEditBookLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(PnlEditBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlEditBookLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnchooseImg))
                            .addComponent(btnEditBook2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlEditBookLayout.createSequentialGroup()
                        .addComponent(lblErrEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(PnlEditBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(txtSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PnlEditBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 676, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookMouseClicked
        int selectedIndex = tblBook.getSelectedRow();
        booksList = BookModify.findAllBooks();
        if (selectedIndex >= 0) {
            Books bk = booksList.get(selectedIndex);
            Image img;
            try {
                img = BookModify.createImageFromByteArray(bk.getImage(), "jpg");
                lblBookImage.setIcon(new ImageIcon(img));
            } catch (IOException ex) {
                Logger.getLogger(BookStorageForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tblBookMouseClicked

    private void lblSearchBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchBookMouseClicked
        String find = txtSearchBook.getText();
        if (find != null && find.length() > 0) {
            lblResetBook.setVisible(true);
            lblSearchBook.setVisible(false);
            booksList = BookModify.searchBook(find);

            tableModelBook.setRowCount(0);
            booksList.forEach((b) -> {
                tableModelBook.addRow(new Object[]{/*tableModel.getRowCount() + 1 ,*/b.getBookId().trim(), b.getBookName(), b.getAuthor(),
                    b.getGenre(), b.getPublisher(), b.getQuantity(), b.getPrice()});
        });
        } else {
            showBook();
        }
    }//GEN-LAST:event_lblSearchBookMouseClicked

    private void lblSearchBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchBookMouseEntered
        HoverEffect.btnSearchHover(btnSearchBook);
    }//GEN-LAST:event_lblSearchBookMouseEntered

    private void lblSearchBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchBookMouseExited
        HoverEffect.btnSearchHoverExt(btnSearchBook);
    }//GEN-LAST:event_lblSearchBookMouseExited

    private void lblResetBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetBookMouseClicked
        lblResetBook.setVisible(false);
        lblSearchBook.setVisible(true);
        showBook();
        txtSearchBook.setText("");
    }//GEN-LAST:event_lblResetBookMouseClicked

    private void lblResetBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetBookMouseEntered
        HoverEffect.btnSearchHover(btnSearchBook);
    }//GEN-LAST:event_lblResetBookMouseEntered

    private void lblResetBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetBookMouseExited
        HoverEffect.btnSearchHoverExt(btnSearchBook);
    }//GEN-LAST:event_lblResetBookMouseExited

    private void lblEditBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditBookMouseClicked
        int selectedIndex = tblBook.getSelectedRow();
        String bookName, author, genre, publisher;
        bookName = txtBookName.getText();
        author = txtAuthor.getText();
        publisher = txtPublisher.getText();
        lblErrEdit.setText("");

        booksList = BookModify.findAllBooks();
        if (selectedIndex >= 0) {
            Books bk = booksList.get(selectedIndex);
            int option = JOptionPane.showConfirmDialog(this, "Do you want to edit this book?");
            //System.out.println(emp.getEmpId());
            if (option == 0) {
                PnlEditBook.setVisible(true);
                jLabel26.setText(bk.getBookId().trim());
                txtBookName.setText(bk.getBookName());
                txtAuthor.setText(bk.getAuthor());
                txtPublisher.setText(bk.getPublisher());
                Image img;
                try {
                    img = BookModify.createImageFromByteArray(bk.getImage(), "jpg");
                    lblEditImg.setIcon(new ImageIcon(img));
                } catch (IOException ex) {
                    Logger.getLogger(BookStorageForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_lblEditBookMouseClicked

    private void lblEditBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditBookMouseEntered
        HoverEffect.btnHover(btnEditBook);
    }//GEN-LAST:event_lblEditBookMouseEntered

    private void lblEditBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditBookMouseExited
        HoverEffect.btnHoverExt(btnEditBook);
    }//GEN-LAST:event_lblEditBookMouseExited

    private void btnchooseImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchooseImgActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".jpg");
                }
            }

            @Override
            public String getDescription() {
                return "Image file (*.jpg)";
            }

            
        });
        if (chooser.showOpenDialog(jPanel9) == JFileChooser.CANCEL_OPTION) {
            return;
        }
        File file = chooser.getSelectedFile();
        try {
            ImageIcon icon = new ImageIcon(file.getPath());
            System.out.println(file.getPath());
            Image img = BookModify.resize(icon.getImage(), 140, 160);
            ImageIcon resizedIcon = new ImageIcon(img);
            lblEditImg.setIcon(resizedIcon);
            //bookImage = BookModify.toByteArray(img, "jpg");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnchooseImgActionPerformed

    private void lblEditBook2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditBook2MouseClicked
        int selectedIndex = tblBook.getSelectedRow();
        String bookId, bookName, author, genre, publisher;
        bookName = txtBookName.getText();
        author = txtAuthor.getText();
        publisher = txtPublisher.getText();
        genre = txtGenre.getSelectedItem().toString();
        bookId = jLabel26.getText();
        ImageIcon icon = (ImageIcon) lblEditImg.getIcon();
        Image img = icon.getImage();

        try {
            bookImage = BookModify.toByteArray(img, "jpg");
        } catch (IOException ex) {
            Logger.getLogger(BookStorageForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (bookName.equals("") || author.equals("") || publisher.equals("") || bookImage == null) {
            lblErrEdit.setText("*Please fill in all fields!");
        } else {

            Books bk = new Books(bookId, bookName, author, genre, publisher, bookImage);
            BookModify.updateOfBookInformation(bk);
            PnlEditBook.setVisible(false);
            showBook();
        }
    }//GEN-LAST:event_lblEditBook2MouseClicked

    private void lblEditBook2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditBook2MouseEntered
        HoverEffect.btnHover(btnEditBook2);
    }//GEN-LAST:event_lblEditBook2MouseEntered

    private void lblEditBook2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditBook2MouseExited
        HoverEffect.btnHoverExt(btnEditBook2);
    }//GEN-LAST:event_lblEditBook2MouseExited

    private void btnEditExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditExitMouseClicked
        PnlEditBook.setVisible(false);
    }//GEN-LAST:event_btnEditExitMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        showBook();
    }//GEN-LAST:event_formMouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        showBook();
    }//GEN-LAST:event_formFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlEditBook;
    private javax.swing.JPanel btnEditBook;
    private javax.swing.JPanel btnEditBook2;
    private javax.swing.JLabel btnEditExit;
    private javax.swing.JPanel btnSearchBook;
    private javax.swing.JButton btnchooseImg;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBookImage;
    private javax.swing.JLabel lblEditBook;
    private javax.swing.JLabel lblEditBook2;
    private javax.swing.JLabel lblEditImg;
    private javax.swing.JLabel lblErrEdit;
    private javax.swing.JLabel lblResetBook;
    private javax.swing.JLabel lblSearchBook;
    private javax.swing.JTable tblBook;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JComboBox<String> txtGenre;
    private javax.swing.JTextField txtPublisher;
    private javax.swing.JTextField txtSearchBook;
    // End of variables declaration//GEN-END:variables
}
