/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Model.Employee;
import Model.EmployeeModify;
import Model.HoverEffect;
import Model.Validation;
import java.awt.Color;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author KHANH VY
 */
public class EmployeeForm extends javax.swing.JPanel {
    
    DefaultTableModel tableModelEmp;
    ArrayList<Employee> employeeList = new ArrayList<>();
    
    
    /**
     * Creates new form EmployeeForm
     */
    public EmployeeForm() {
        initComponents();
        tableModelEmp = (DefaultTableModel) tblEmployee.getModel();
        lblEdit2.setVisible(false);
        lblReset.setVisible(false);
        showEmployee();
    }

    // Method to automatically display value to table
    public void showEmployee() {
        employeeList = EmployeeModify.findAll();
        tableModelEmp.setRowCount(0);
        employeeList.forEach((e) -> {
            tableModelEmp.addRow(new Object[]{
                e.getEmpId(),
                e.getEmpName(),
                e.getAddress(),
                e.getBirthday(),
                e.getStartDate(),
                e.getPosition(),
                e.getSalary()});
        });
    }
    
    
    public void checkSalary() {
        String salary = txtSalary.getText().replace(",", "");
        if (salary.matches("\\d+")) {
            long salary2 = Long.parseLong(salary);
            if (salary2 < 4000000) {
                lblValErr2.setText("Salary must greater than or equal to 4.000.000!");
            } else {
                lblValErr2.setText("");
            }
        } else {
            lblValErr2.setText("*Accept digit only!");         
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Card3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDob = new com.toedter.calendar.JDateChooser();
        txtPass = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        txtStart = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtConpass = new javax.swing.JPasswordField();
        txtPosition = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        btnAddEmp = new javax.swing.JPanel();
        lblAddEmp = new javax.swing.JLabel();
        lblEdit2 = new javax.swing.JLabel();
        lblValErr = new javax.swing.JLabel();
        lblValErr2 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JPanel();
        lblDelete = new javax.swing.JLabel();
        btnEdit = new javax.swing.JPanel();
        lblEdit = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        lblReset = new javax.swing.JLabel();
        lblValErr1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        Card3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblEmployee.setAutoCreateRowSorter(true);
        tblEmployee.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblEmployee.setForeground(new java.awt.Color(153, 153, 153));
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Address", "Birthday", "Start Date", "Position", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployee.setGridColor(new java.awt.Color(255, 255, 255));
        tblEmployee.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblEmployee.setRowHeight(25);
        tblEmployee.setSelectionBackground(new java.awt.Color(0, 181, 204));
        jScrollPane1.setViewportView(tblEmployee);

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Name:");

        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("D.O.B:");

        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Username:");

        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Address:");

        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Password:");

        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Confirm Password:");

        txtDob.setForeground(new java.awt.Color(153, 153, 153));

        txtPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Start date:");

        txtStart.setForeground(new java.awt.Color(153, 153, 153));

        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Position:");

        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Salary:");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(153, 153, 153));
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(153, 153, 153));
        txtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUser.setForeground(new java.awt.Color(153, 153, 153));
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserKeyReleased(evt);
            }
        });

        txtConpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtConpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConpassKeyReleased(evt);
            }
        });

        txtPosition.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPosition.setForeground(new java.awt.Color(153, 153, 153));
        txtPosition.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtSalary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSalary.setForeground(new java.awt.Color(153, 153, 153));
        txtSalary.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtSalary.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSalaryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSalaryFocusLost(evt);
            }
        });
        txtSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSalaryKeyReleased(evt);
            }
        });

        btnAddEmp.setBackground(new java.awt.Color(0, 181, 204));

        lblAddEmp.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblAddEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblAddEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addEmp.png"))); // NOI18N
        lblAddEmp.setText("Add Employee");
        lblAddEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddEmpMouseExited(evt);
            }
        });

        lblEdit2.setFont(new java.awt.Font("Trebuchet MS", 0, 19)); // NOI18N
        lblEdit2.setForeground(new java.awt.Color(255, 255, 255));
        lblEdit2.setText("          Edit");
        lblEdit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEdit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEdit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEdit2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAddEmpLayout = new javax.swing.GroupLayout(btnAddEmp);
        btnAddEmp.setLayout(btnAddEmpLayout);
        btnAddEmpLayout.setHorizontalGroup(
            btnAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddEmpLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(btnAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEdit2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddEmp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAddEmpLayout.setVerticalGroup(
            btnAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddEmpLayout.createSequentialGroup()
                .addComponent(lblAddEmp)
                .addGap(2, 2, 2)
                .addComponent(lblEdit2))
        );

        lblValErr.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblValErr.setForeground(new java.awt.Color(255, 51, 51));

        lblValErr2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblValErr2.setForeground(new java.awt.Color(255, 51, 51));

        btnDelete.setBackground(new java.awt.Color(0, 181, 204));

        lblDelete.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblDelete.setForeground(new java.awt.Color(255, 255, 255));
        lblDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        lblDelete.setText(" Delete");
        lblDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDeleteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDeleteLayout = new javax.swing.GroupLayout(btnDelete);
        btnDelete.setLayout(btnDeleteLayout);
        btnDeleteLayout.setHorizontalGroup(
            btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDeleteLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnDeleteLayout.setVerticalGroup(
            btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        btnEdit.setBackground(new java.awt.Color(0, 181, 204));

        lblEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        lblEdit.setText("Edit");
        lblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEditMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEditLayout = new javax.swing.GroupLayout(btnEdit);
        btnEdit.setLayout(btnEditLayout);
        btnEditLayout.setHorizontalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnEditLayout.setVerticalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        txtSearch.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(153, 153, 153));
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));

        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search2.png"))); // NOI18N
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSearchMouseExited(evt);
            }
        });

        lblReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        lblReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblResetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSearchLayout = new javax.swing.GroupLayout(btnSearch);
        btnSearch.setLayout(btnSearchLayout);
        btnSearchLayout.setHorizontalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSearchLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblSearch)
                .addGap(3, 3, 3)
                .addComponent(lblReset, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        btnSearchLayout.setVerticalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSearchLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblValErr1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblValErr1.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout Card3Layout = new javax.swing.GroupLayout(Card3);
        Card3.setLayout(Card3Layout);
        Card3Layout.setHorizontalGroup(
            Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(Card3Layout.createSequentialGroup()
                .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Card3Layout.createSequentialGroup()
                        .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Card3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Card3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Card3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Card3Layout.createSequentialGroup()
                                .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel11))
                                .addGap(40, 40, 40)
                                .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Card3Layout.createSequentialGroup()
                                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(441, 441, 441))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Card3Layout.createSequentialGroup()
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Card3Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblValErr, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblValErr2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(Card3Layout.createSequentialGroup()
                                .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Card3Layout.createSequentialGroup()
                                        .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel10))
                                        .addGap(31, 31, 31)
                                        .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Card3Layout.createSequentialGroup()
                                                .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(txtPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtConpass, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(Card3Layout.createSequentialGroup()
                                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblValErr1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(Card3Layout.createSequentialGroup()
                                        .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel15))
                                        .addGap(31, 31, 31)
                                        .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(36, 36, 36)))))
                .addContainerGap())
        );
        Card3Layout.setVerticalGroup(
            Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Card3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Card3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel9)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblValErr1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Card3Layout.createSequentialGroup()
                        .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtConpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Card3Layout.createSequentialGroup()
                        .addComponent(lblValErr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblValErr2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 979, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Card3, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Card3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyReleased
        Validation.checkSpace(txtUser, lblValErr1);
    }//GEN-LAST:event_txtUserKeyReleased

    private void txtConpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConpassKeyReleased
        Validation.checkPass(txtPass, txtConpass, lblValErr);
    }//GEN-LAST:event_txtConpassKeyReleased

    private void txtSalaryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalaryFocusGained
        //txtSalary.setText("");
    }//GEN-LAST:event_txtSalaryFocusGained

    private void txtSalaryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalaryFocusLost
        Validation.formatNumber(txtSalary);
    }//GEN-LAST:event_txtSalaryFocusLost

    private void txtSalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalaryKeyReleased
        checkSalary();
    }//GEN-LAST:event_txtSalaryKeyReleased

    private void lblAddEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddEmpMouseClicked
        String name, address, user, pass, conpass, position, salary;
        Date dob, startdate;
        
        name = txtName.getText();
        address = txtAddress.getText();
        user = txtUser.getText();
        pass = txtPass.getText();
        conpass = txtConpass.getText();
        position = txtPosition.getText();
        salary = txtSalary.getText();
        dob = txtDob.getDate();
        startdate = txtStart.getDate();
       
        if (name.equals("")
            || address.equals("")
            || user.equals("")
            || pass.equals("")
            || conpass.equals("")
            || position.equals("")
            || salary.equals("")
            || dob == null
            || startdate == null) {
            lblValErr2.setText("*Please fill in all fields!");
        } else if (lblValErr.getText().equals("") & lblValErr.getText().equals("") ) {

            long salarynum = Long.parseLong(txtSalary.getText().replace(",", ""));
            Employee emp = new Employee(name, user, pass, address, position, dob, startdate, salarynum);
            EmployeeModify.insert(emp);
            Validation.Notify(this, "Add successful!", "Message");
            showEmployee();

            txtName.setText("");
            txtAddress.setText("");
            txtUser.setText("");
            txtPass.setText("");
            txtConpass.setText("");
            txtPosition.setText("");
            txtSalary.setText("");
            txtDob.setDate(null);
            txtStart.setDate(null);
            lblValErr2.setText("");

        }
    }//GEN-LAST:event_lblAddEmpMouseClicked

    private void lblAddEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddEmpMouseEntered
        HoverEffect.btnHover(btnAddEmp);
    }//GEN-LAST:event_lblAddEmpMouseEntered

    private void lblAddEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddEmpMouseExited
        HoverEffect.btnHoverExt(btnAddEmp);
    }//GEN-LAST:event_lblAddEmpMouseExited

    private void lblEdit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEdit2MouseClicked
        int selectedIndex = tblEmployee.getSelectedRow();
        if (selectedIndex >= 0) {
            Employee emp = employeeList.get(selectedIndex);
            int id = emp.getEmpId();
            String name, address, user, pass, conpass, position, salary;
            Date dob, startdate;
            
            name = txtName.getText();
            address = txtAddress.getText();
            user = txtUser.getText();
            pass = txtPass.getText();
            conpass = txtConpass.getText();
            position = txtPosition.getText();
            salary = txtSalary.getText();
            dob = txtDob.getDate();
            startdate = txtStart.getDate();
            if (name.equals("")
                || address.equals("")
                || user.equals("")
                || pass.equals("")
                || conpass.equals("")
                || position.equals("")
                || salary.equals("")
                || dob == null
                || startdate == null) {
                lblValErr2.setText("*Please fill in all fields!");
            } else if (lblValErr.getText().equals("") & lblValErr.getText().equals("")) {

                long salarynum = Long.parseLong(txtSalary.getText().replace(",", ""));
                Employee emp1 = new Employee(id, name, user, pass, address, position, dob, startdate, salarynum);
                EmployeeModify.update(emp1);
                Validation.Notify(this, "Edit successful!", "Message");
                showEmployee();

                txtName.setText("");
                txtAddress.setText("");
                txtUser.setText("");
                txtPass.setText("");
                txtConpass.setText("");
                txtPosition.setText("");
                txtSalary.setText("");
                txtDob.setDate(null);
                txtStart.setDate(null);
                lblValErr2.setText("");
                lblEdit2.setVisible(false);
                lblAddEmp.setVisible(true);
                btnEdit.setVisible(true);
                btnDelete.setVisible(true);
            }
        }
    }//GEN-LAST:event_lblEdit2MouseClicked

    private void lblEdit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEdit2MouseEntered
        HoverEffect.btnHover(btnAddEmp);
    }//GEN-LAST:event_lblEdit2MouseEntered

    private void lblEdit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEdit2MouseExited
        HoverEffect.btnHoverExt(btnAddEmp);
    }//GEN-LAST:event_lblEdit2MouseExited

    private void lblDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseClicked
        int selectedIndex = tblEmployee.getSelectedRow();
        employeeList = EmployeeModify.findAll();
        if (selectedIndex >= 0) {
            Employee emp = employeeList.get(selectedIndex);
            int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this person?");
            //System.out.println(emp.getEmpId());
            if (option == 0) {
                EmployeeModify.delete(emp.getEmpId());
                showEmployee();
                EmployeeModify.resetIncrement();
            }

        }
    }//GEN-LAST:event_lblDeleteMouseClicked

    private void lblDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseEntered
        HoverEffect.btnHover(btnDelete);
    }//GEN-LAST:event_lblDeleteMouseEntered

    private void lblDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseExited
        HoverEffect.btnHoverExt(btnDelete);
    }//GEN-LAST:event_lblDeleteMouseExited

    private void lblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseClicked
        int selectedIndex = tblEmployee.getSelectedRow();
        String name, address, user, pass, conpass, position, salary;
        Date dob, startdate;
        name = txtName.getText();
        address = txtAddress.getText();
        user = txtUser.getText();
        pass = txtPass.getText();
        conpass = txtConpass.getText();
        position = txtPosition.getText();
        salary = txtSalary.getText();

        dob = txtDob.getDate();
        startdate = txtStart.getDate();

        employeeList = EmployeeModify.findAll();
        if (selectedIndex >= 0) {
            Employee emp = employeeList.get(selectedIndex);
            int option = JOptionPane.showConfirmDialog(this, "Do you want to edit this person?");
            //System.out.println(emp.getEmpId());
            if (option == 0) {
                btnEdit.setVisible(false);
                btnDelete.setVisible(false);
                txtName.setText(emp.getEmpName());
                txtAddress.setText(emp.getAddress());
                txtUser.setText(emp.getUserName());
                txtPass.setText(emp.getPassword());
                txtConpass.setText(emp.getPassword());
                txtPosition.setText(emp.getPosition());
                txtSalary.setText(Long.toString(emp.getSalary()));
                txtDob.setDate(emp.getBirthday());
                txtStart.setDate(emp.getStartDate());

                lblAddEmp.setVisible(false);
                lblEdit2.setVisible(true);
                lblValErr.setText("");
                lblValErr2.setText("");
                Validation.formatNumber(txtSalary);
            }
        }
    }//GEN-LAST:event_lblEditMouseClicked

    private void lblEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseEntered
        HoverEffect.btnHover(btnEdit);
    }//GEN-LAST:event_lblEditMouseEntered

    private void lblEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseExited
        HoverEffect.btnHoverExt(btnEdit);
    }//GEN-LAST:event_lblEditMouseExited

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked

        String find = txtSearch.getText();
        if (find != null && find.length() > 0) {
            lblReset.setVisible(true);
            lblSearch.setVisible(false);
            employeeList = EmployeeModify.search(find);

            tableModelEmp.setRowCount(0);
            employeeList.forEach((e) -> {
                tableModelEmp.addRow(new Object[]{/*tableModel.getRowCount() + 1 ,*/e.getEmpId(), e.getEmpName(),
                    e.getAddress(), e.getBirthday(), e.getStartDate(), e.getPosition(), e.getSalary()});
        });
        } else {
            showEmployee();
        }
    }//GEN-LAST:event_lblSearchMouseClicked

    private void lblSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseEntered
        HoverEffect.btnSearchHover(btnSearch);
    }//GEN-LAST:event_lblSearchMouseEntered

    private void lblSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseExited
        HoverEffect.btnSearchHover(btnSearch);
    }//GEN-LAST:event_lblSearchMouseExited

    private void lblResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseClicked
        lblReset.setVisible(false);
        lblSearch.setVisible(true);
        showEmployee();
        txtSearch.setText("");
    }//GEN-LAST:event_lblResetMouseClicked

    private void lblResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseEntered
        HoverEffect.btnSearchHover(btnSearch);
    }//GEN-LAST:event_lblResetMouseEntered

    private void lblResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseExited
        HoverEffect.btnSearchHover(btnSearch);
    }//GEN-LAST:event_lblResetMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Card3;
    private javax.swing.JPanel btnAddEmp;
    private javax.swing.JPanel btnDelete;
    private javax.swing.JPanel btnEdit;
    private javax.swing.JPanel btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAddEmp;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblEdit2;
    private javax.swing.JLabel lblReset;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblValErr;
    private javax.swing.JLabel lblValErr1;
    private javax.swing.JLabel lblValErr2;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JPasswordField txtConpass;
    private com.toedter.calendar.JDateChooser txtDob;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearch;
    private com.toedter.calendar.JDateChooser txtStart;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
