/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Model.BookModify;
import Model.Books;
import Model.HoverEffect;
import Model.Import;
import Model.Validation;
import java.util.ArrayList;
import java.util.Date;
import Form.BookStorageForm;

/**
 *
 * @author KHANH VY
 */
public class ImportBookForm extends javax.swing.JPanel {
    ArrayList<Books> booksList = new ArrayList<>();
    ArrayList<Import> importList = new ArrayList<>();
    /**
     * Creates new form ImportBookForm
     */
    public ImportBookForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtBookId = new javax.swing.JTextField();
        txtDate = new com.toedter.calendar.JDateChooser();
        txtQuantity = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtDiscount = new javax.swing.JTextField();
        btnAddBooks = new javax.swing.JPanel();
        lblAddBooks = new javax.swing.JLabel();
        lblErr = new javax.swing.JLabel();
        lblBookErr = new javax.swing.JLabel();
        lblBookErr1 = new javax.swing.JLabel();
        lblBookErr2 = new javax.swing.JLabel();
        lblBookErr3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 32)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 181, 204));
        jLabel17.setText("ADD TO STORAGE");

        jPanel11.setBackground(new java.awt.Color(0, 181, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Date");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Book ID");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Discount(%)");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Quantity");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Price (1pcs)");

        txtBookId.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        txtBookId.setForeground(new java.awt.Color(204, 204, 204));
        txtBookId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtBookId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBookIdKeyReleased(evt);
            }
        });

        txtQuantity.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(204, 204, 204));
        txtQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });

        txtPrice.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(204, 204, 204));
        txtPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriceFocusLost(evt);
            }
        });
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });

        txtDiscount.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        txtDiscount.setForeground(new java.awt.Color(204, 204, 204));
        txtDiscount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscountKeyReleased(evt);
            }
        });

        btnAddBooks.setBackground(new java.awt.Color(0, 181, 204));

        lblAddBooks.setBackground(new java.awt.Color(255, 255, 255));
        lblAddBooks.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        lblAddBooks.setForeground(new java.awt.Color(255, 255, 255));
        lblAddBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add2.png"))); // NOI18N
        lblAddBooks.setText("Add");
        lblAddBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddBooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddBooksMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAddBooksLayout = new javax.swing.GroupLayout(btnAddBooks);
        btnAddBooks.setLayout(btnAddBooksLayout);
        btnAddBooksLayout.setHorizontalGroup(
            btnAddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAddBooksLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(lblAddBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnAddBooksLayout.setVerticalGroup(
            btnAddBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddBooksLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblAddBooks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblErr.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        lblErr.setForeground(new java.awt.Color(255, 51, 51));

        lblBookErr.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        lblBookErr.setForeground(new java.awt.Color(255, 0, 51));

        lblBookErr1.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        lblBookErr1.setForeground(new java.awt.Color(255, 0, 51));

        lblBookErr2.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        lblBookErr2.setForeground(new java.awt.Color(255, 0, 51));

        lblBookErr3.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        lblBookErr3.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(88, 88, 88)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDiscount)
                                    .addComponent(txtPrice)
                                    .addComponent(txtQuantity)
                                    .addComponent(txtBookId)
                                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBookErr2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBookErr1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBookErr3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBookErr, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBookErr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel19)
                                            .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(47, 47, 47)
                                .addComponent(jLabel18)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblBookErr1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblBookErr2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblBookErr3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblErr, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(97, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBookIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBookIdKeyReleased
        Validation.checkSpace(txtBookId, lblBookErr);
    }//GEN-LAST:event_txtBookIdKeyReleased

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        Validation.checkDigit(txtQuantity, lblBookErr1);
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void txtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusLost
        Validation.formatNumber(txtPrice);
    }//GEN-LAST:event_txtPriceFocusLost

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        Validation.checkDigit(txtPrice, lblBookErr2);
    }//GEN-LAST:event_txtPriceKeyReleased

    private void txtDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountKeyReleased
        Validation.checkDiscount(txtDiscount, lblBookErr3);
    }//GEN-LAST:event_txtDiscountKeyReleased

    private void lblAddBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddBooksMouseClicked
        booksList = BookModify.findAllBooks();

        String bookid, quantity, price, discount;
        Date date;
        quantity = txtQuantity.getText();
        bookid = txtBookId.getText();
        date = txtDate.getDate();
        price = txtPrice.getText();
        discount = txtDiscount.getText();

        if (bookid == "" || quantity == "" || date == null || price == "" || discount == "" ||
            !lblBookErr1.getText().equals("") || !lblBookErr2.getText().equals("") || !lblBookErr3.getText().equals("")) {
            lblErr.setText("*All fields must be filled in!");
        } else {
            int count = 0;
            for (int i = 0; i < booksList.size(); i++) {
                if (booksList.get(i).getBookId().trim().equals(bookid)) {
                    count++; break;
                }
            }
            if (count==0) {
                String txt1 = bookid;
                String txt2 = quantity;
                String txt3 = price;
                BookAdding addBooks = new BookAdding(txt1, txt2, txt3);

                addBooks.show();

            } else if(count ==1) {
                int quantity1 = Integer.parseInt(quantity);
                long price1 = Long.parseLong(price.replace(",", ""));
                float discount1 = Float.parseFloat(discount);
                Import imp = new Import(quantity1, bookid, date, price1, discount1);
                BookModify.inserttoImport(imp);

                Validation.Notify(this, "Add success!", "Message");
                
                //showStorageTracking();

                int getIndex;
                for(getIndex = 0; getIndex < booksList.size(); getIndex++) {
                    if (booksList.get(getIndex).getBookId().trim().equals(bookid)) {
                        getIndex++; break;
                    }
                }
                String updateBook = booksList.get(getIndex-1).getBookId();
                int newQuantity = Integer.parseInt(quantity) + booksList.get(getIndex-1).getQuantity();
                long newPrice = Long.parseLong(price.replace(",", ""));

                Books bk1 = new Books(updateBook, newQuantity, newPrice);
                BookModify.updateOfBookPrice(bk1);
                
                //showBook();

                txtQuantity.setText("");
                txtBookId.setText("");
                txtDate.setDate(null);
                txtPrice.setText("");
                txtDiscount.setText("");
                lblErr.setText("");
            }
        }
    }//GEN-LAST:event_lblAddBooksMouseClicked

    private void lblAddBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddBooksMouseEntered
        HoverEffect.btnHover(btnAddBooks);
    }//GEN-LAST:event_lblAddBooksMouseEntered

    private void lblAddBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddBooksMouseExited
        HoverEffect.btnHoverExt(btnAddBooks);
    }//GEN-LAST:event_lblAddBooksMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAddBooks;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JLabel lblAddBooks;
    private javax.swing.JLabel lblBookErr;
    private javax.swing.JLabel lblBookErr1;
    private javax.swing.JLabel lblBookErr2;
    private javax.swing.JLabel lblBookErr3;
    private javax.swing.JLabel lblErr;
    private javax.swing.JTextField txtBookId;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
