/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Pattern.ExportModify;
import Pattern.Validation;
import Pattern.ReceiptDetail;
import Pattern.ReceiptDetailModify;
import Pattern.Export;
import Pattern.ExportModify;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author KHANH VY
 */
public class ReceiptForm extends javax.swing.JPanel {
    DefaultTableModel tableModelReceipt;
    ArrayList<ReceiptDetail> receiptList = new ArrayList<>();
    Date today = new java.util.Date();
    
  
    
    public static class SequentialNumber {
        public static int init() {
            int currentNumber;
            Export export = new Export();
            export = ExportModify.selectTop1Export();
            if (export == null) {
                currentNumber = 1000;
            } else {
                String id = export.getReceiptId().replace("R", "");
                currentNumber = Integer.parseInt(id.trim());
            }
            return currentNumber;
        }
       
    //private static int currentNumber = 1000;    
   
        public static String GetNextNumber(int currentNumber) {
            currentNumber++;
            return "R" + currentNumber;

        }
    }

    public ReceiptForm() {
        initComponents();
        tableModelReceipt = (DefaultTableModel) tblReceipt.getModel();
        int currentId = SequentialNumber.init();
        String stt = SequentialNumber.GetNextNumber(currentId);
        lblReceiptId.setText(stt);
        
    }
    
    public void showReceiptDetail(String receipid) {
        receiptList = ReceiptDetailModify.findAllReceipt(receipid);
        tableModelReceipt.setRowCount(0);
        receiptList.forEach((r) -> {
            tableModelReceipt.addRow(new Object[]{/*tableModel.getRowCount() + 1 ,*/r.getBookName(), r.getQuantity(),
                r.getDiscount(), r.getPrice(), r.getTotal()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBookId = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblAddReceipt = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblDeleteReceiptRow = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReceipt = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        lblPrint = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblReceiptId = new javax.swing.JLabel();
        lblError1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 181, 204));
        setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(3, 680));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("BookId");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Quantity");

        txtBookId.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtBookId.setForeground(new java.awt.Color(204, 204, 204));
        txtBookId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        txtQuantity.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(204, 204, 204));
        txtQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 181, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lblAddReceipt.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        lblAddReceipt.setForeground(new java.awt.Color(255, 255, 255));
        lblAddReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add2.png"))); // NOI18N
        lblAddReceipt.setText(" Add");
        lblAddReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddReceiptMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblAddReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 181, 204));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        lblDeleteReceiptRow.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        lblDeleteReceiptRow.setForeground(new java.awt.Color(255, 255, 255));
        lblDeleteReceiptRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        lblDeleteReceiptRow.setText("Delete");
        lblDeleteReceiptRow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteReceiptRowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDeleteReceiptRow, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(lblDeleteReceiptRow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tblReceipt.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblReceipt.setForeground(new java.awt.Color(153, 153, 153));
        tblReceipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookName", "Quantity", "Discount", "Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReceipt.setGridColor(new java.awt.Color(255, 255, 255));
        tblReceipt.setRowHeight(25);
        tblReceipt.setSelectionBackground(new java.awt.Color(0, 181, 204));
        jScrollPane1.setViewportView(tblReceipt);
        if (tblReceipt.getColumnModel().getColumnCount() > 0) {
            tblReceipt.getColumnModel().getColumn(1).setPreferredWidth(3);
            tblReceipt.getColumnModel().getColumn(2).setPreferredWidth(3);
            tblReceipt.getColumnModel().getColumn(3).setPreferredWidth(7);
            tblReceipt.getColumnModel().getColumn(4).setPreferredWidth(7);
        }

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Total Amount");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("(Including VAT)");

        lblTotal.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(102, 102, 102));
        lblTotal.setText("0");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Discount");

        txtDiscount.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        txtDiscount.setForeground(new java.awt.Color(204, 204, 204));
        txtDiscount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jPanel4.setBackground(new java.awt.Color(0, 181, 204));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" Proceed to Check out");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel5.setBackground(new java.awt.Color(0, 181, 204));

        lblPrint.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        lblPrint.setForeground(new java.awt.Color(255, 255, 255));
        lblPrint.setText("     Print");
        lblPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrintMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPrint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Receipt Id:");

        lblReceiptId.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        lblReceiptId.setForeground(new java.awt.Color(102, 102, 102));

        lblError1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblError1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(43, 43, 43)
                                .addComponent(lblReceiptId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblError1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblReceiptId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBookId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblError1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTotal))
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintMouseClicked
        int currentId = SequentialNumber.init();
        String stt = SequentialNumber.GetNextNumber(currentId);
        lblReceiptId.setText(stt);
        projectsem2.Books bk = Pattern.ReceiptDetailModify.searchBookId("aaa");
        System.out.println(bk.getPrice());
    }//GEN-LAST:event_lblPrintMouseClicked

    //Add Receipt Detail
    private void lblAddReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddReceiptMouseClicked
        
        // Create new ReceiptId in table Export
        Export exp = ExportModify.searchExportReceiptId(lblReceiptId.getText());
        if (exp ==null) {
            ExportModify.insertToExport(lblReceiptId.getText());
        }
        
        String bookId, quantity, price, discount;
        bookId = txtBookId.getText();
        quantity = txtQuantity.getText();
        discount = txtDiscount.getText();
        lblError.setText("");
        
        if (bookId.equals("") || quantity.equals("")) {
            lblError.setText("*Please fill in BookId and Quantity");
        } else if (lblError1.getText().equals("")) {
            int discountNum;
            int quantityNum = Integer.parseInt(quantity);
            if (discount.equals("")) {
                discountNum = 0;
            } else {
                discountNum = Integer.parseInt(discount);
            }
            projectsem2.Books bk = Pattern.ReceiptDetailModify.searchBookId(bookId);
            if (bk == null) {
                Validation.Notify(this, "No BookId found!", "Error");
            } else {
                Pattern.ReceiptDetail rcp1 = Pattern.ReceiptDetailModify.searchReceipIdBookId(lblReceiptId.getText(), bookId);
                if (rcp1 == null) {

                    tableModelReceipt.addRow(new Object[]{/*tableModelReceipt.getRowCount() + 1,*/bk.getBookName(), quantity,
                        discount, bk.getPrice(), quantityNum * bk.getPrice() * (100 - discountNum) / 100});

                    Pattern.ReceiptDetail rcp = new Pattern.ReceiptDetail();
                    rcp.setReceiptId(lblReceiptId.getText());
                    rcp.setBookName(bk.getBookName());
                    rcp.setBookId(bookId);
                    rcp.setQuantity(quantityNum);
                    rcp.setPrice(bk.getPrice());
                    rcp.setDiscount(discountNum);
                    rcp.setEmpId(0);  // NOT CODE YET!!!!!!!
                    rcp.setTotal(quantityNum * bk.getPrice() * (100 - discountNum) / 100);
                    
                    Long currentTotal = Long.parseLong(lblTotal.getText());
                    Long newTotal = rcp.getTotal() + currentTotal;
                    String newTotal1 = Long.toString(newTotal);
                    lblTotal.setText(newTotal1);
                    
                    ReceiptDetailModify.insertToReceiptDetail(rcp);
                    
                    //UPDATE EXPORT TABLE
                    exp.setReceiptId(lblReceiptId.getText());
                    exp.setDate(today);
                    exp.setTotal(newTotal);
                    exp.setEmpId(0); // NOT CODE YET!!!!!
                    ExportModify.updateExport(exp);
                    
                } else {
                    
                    int newQuantity = rcp1.getQuantity();
                    rcp1.setQuantity(quantityNum + newQuantity);
                    
                    long updateTotal = rcp1.getTotal();
                    rcp1.setTotal(updateTotal + quantityNum * bk.getPrice() * (100 - discountNum) / 100);
                    
                    Long currentTotal = Long.parseLong(lblTotal.getText());
                    Long newTotal = quantityNum * rcp1.getPrice() * (100 - discountNum) / 100 + currentTotal;
                    String newTotal1 = Long.toString(newTotal);
                    lblTotal.setText(newTotal1);
                    
                    ReceiptDetailModify.updateReceiptDetail(rcp1);
                    showReceiptDetail(lblReceiptId.getText());
                    
                    //UPDATE EXPORT TABLE
                    exp.setReceiptId(lblReceiptId.getText());
                    exp.setDate(today);
                    exp.setTotal(newTotal);
                    exp.setEmpId(0); // NOT CODE YET!!!!!
                    ExportModify.updateExport(exp);
                }
            }
        }
    }//GEN-LAST:event_lblAddReceiptMouseClicked
    
    
    private void lblDeleteReceiptRowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteReceiptRowMouseClicked
        int selectedIndex = tblReceipt.getSelectedRow();
        String bookId = tblReceipt.getModel().getValueAt(selectedIndex, 0).toString();
        String total = tblReceipt.getModel().getValueAt(selectedIndex, 4).toString();
        
        Long currentTotal = Long.parseLong(lblTotal.getText());
        Long newTotal = currentTotal - Long.parseLong(total);
        String newTotal1 = Long.toString(newTotal);
        
        int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this?");
        
        if (option == 0) {
            ReceiptDetailModify.deleteReceipDetailRow(lblReceiptId.getText(), bookId);
            showReceiptDetail(lblReceiptId.getText());
            lblTotal.setText(newTotal1);

            //UPDATE EXPORT TABLE
            Export exp = new Export();
            exp.setReceiptId(lblReceiptId.getText());
            exp.setDate(today);
            exp.setTotal(newTotal);
            exp.setEmpId(0); // NOT CODE YET!!!!!
            ExportModify.updateExport(exp);
        }
    }//GEN-LAST:event_lblDeleteReceiptRowMouseClicked

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        Pattern.Validation.checkDigit(txtQuantity, lblError1);
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityKeyPressed
    
    // Sua Quantity trong table book
    // PROCEED TO CHECKOUT
    //add du lieu cua hoa don vao bang export
    // xoa bang
    // hien thi Trang in hoa don
    //PRINT
    //Xoa trang in hoa don
    //Reset lai ma hoa don
    // 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAddReceipt;
    private javax.swing.JLabel lblDeleteReceiptRow;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblPrint;
    private javax.swing.JLabel lblReceiptId;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblReceipt;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
