/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Model.BookModify;
import Model.HoverEffect;
import Model.Import;
import Model.Validation;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KHANH VY
 */
public class StorageTrackingForm extends javax.swing.JPanel {
    ArrayList<Import> importList = new ArrayList<>();
    DefaultTableModel tableModelImport;
    
    
    /**
     * Creates new form StorageTrackingForm
     */
    public StorageTrackingForm() {
        initComponents();
        tableModelImport = (DefaultTableModel) tblStorageTracking.getModel();
        showStorageTracking();
        lblStrgTrackReset.setVisible(false);
    }

    
    public void showStorageTracking() {
        //employeeList = EmployeeModify.findAll();
        importList = BookModify.findAllStorageTracking();

        tableModelImport.setRowCount(0);
        importList.forEach((imp) -> {
            tableModelImport.addRow(new Object[]{/*tableModel.getRowCount() + 1 ,*/imp.getBookid().trim(), imp.getDate(),
                imp.getQuantity(), imp.getPrice(), imp.getDiscount()});
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblStorageTracking = new javax.swing.JTable();
        txtSearchStrgTrack = new javax.swing.JTextField();
        btnStrgTrackSearch = new javax.swing.JPanel();
        lblStrgTrackSearch = new javax.swing.JLabel();
        lblStrgTrackReset = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        tblStorageTracking.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblStorageTracking.setForeground(new java.awt.Color(153, 153, 153));
        tblStorageTracking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "BookId", "Date", "Quantity", "Price (1pcs)", "Discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStorageTracking.setGridColor(new java.awt.Color(255, 255, 255));
        tblStorageTracking.setRowHeight(25);
        tblStorageTracking.setSelectionBackground(new java.awt.Color(0, 181, 204));
        jScrollPane3.setViewportView(tblStorageTracking);

        txtSearchStrgTrack.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        txtSearchStrgTrack.setForeground(new java.awt.Color(204, 204, 204));
        txtSearchStrgTrack.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        btnStrgTrackSearch.setBackground(new java.awt.Color(255, 255, 255));

        lblStrgTrackSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search2.png"))); // NOI18N
        lblStrgTrackSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStrgTrackSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStrgTrackSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStrgTrackSearchMouseExited(evt);
            }
        });

        lblStrgTrackReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        lblStrgTrackReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStrgTrackResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStrgTrackResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStrgTrackResetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnStrgTrackSearchLayout = new javax.swing.GroupLayout(btnStrgTrackSearch);
        btnStrgTrackSearch.setLayout(btnStrgTrackSearchLayout);
        btnStrgTrackSearchLayout.setHorizontalGroup(
            btnStrgTrackSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStrgTrackSearchLayout.createSequentialGroup()
                .addComponent(lblStrgTrackSearch)
                .addGap(4, 4, 4)
                .addComponent(lblStrgTrackReset))
        );
        btnStrgTrackSearchLayout.setVerticalGroup(
            btnStrgTrackSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStrgTrackSearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btnStrgTrackSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStrgTrackReset)
                    .addComponent(lblStrgTrackSearch)))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSearchStrgTrack, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnStrgTrackSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchStrgTrack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStrgTrackSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblStrgTrackSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStrgTrackSearchMouseClicked
        String find = txtSearchStrgTrack.getText();
        if (find != null && find.length() > 0) {
            lblStrgTrackReset.setVisible(true);
            lblStrgTrackSearch.setVisible(false);
            importList = BookModify.searchStorageTracking(find);

            tableModelImport.setRowCount(0);
            importList.forEach((b) -> {
                tableModelImport.addRow(new Object[]{/*tableModel.getRowCount() + 1 ,*/b.getBookid().trim(), b.getDate(), b.getQuantity()
                    , b.getPrice(), b.getDiscount()});
        });
        } else {
            showStorageTracking();
        }
    }//GEN-LAST:event_lblStrgTrackSearchMouseClicked

    private void lblStrgTrackSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStrgTrackSearchMouseEntered
        HoverEffect.btnSearchHover(btnStrgTrackSearch);
    }//GEN-LAST:event_lblStrgTrackSearchMouseEntered

    private void lblStrgTrackSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStrgTrackSearchMouseExited
        HoverEffect.btnSearchHoverExt(btnStrgTrackSearch);
    }//GEN-LAST:event_lblStrgTrackSearchMouseExited

    private void lblStrgTrackResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStrgTrackResetMouseClicked
        lblStrgTrackReset.setVisible(false);
        lblStrgTrackSearch.setVisible(true);
        showStorageTracking();
        txtSearchStrgTrack.setText("");
    }//GEN-LAST:event_lblStrgTrackResetMouseClicked

    private void lblStrgTrackResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStrgTrackResetMouseEntered
        HoverEffect.btnSearchHover(btnStrgTrackSearch);
    }//GEN-LAST:event_lblStrgTrackResetMouseEntered

    private void lblStrgTrackResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStrgTrackResetMouseExited
        HoverEffect.btnSearchHoverExt(btnStrgTrackSearch);
    }//GEN-LAST:event_lblStrgTrackResetMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnStrgTrackSearch;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblStrgTrackReset;
    private javax.swing.JLabel lblStrgTrackSearch;
    private javax.swing.JTable tblStorageTracking;
    private javax.swing.JTextField txtSearchStrgTrack;
    // End of variables declaration//GEN-END:variables
}
